PROGRAM:=$(BIN_DIR)/tangram_filter.pl $(BIN_DIR)/tangram_view_scan_file.py

$(PROGRAM): tangram_filter.pl tangram_view_scan_file.py
	@echo "  * copying $(PROGRAM)"
	@cp tangram_filter.pl $(BIN_DIR)/
	@cp tangram_view_scan_file.py $(BIN_DIR)/
